### ISSUE TITLE
Do colours for directories work on MacOS?

### ISSUE THREAD

**Issue by ayroblu** [jpwilliams/gitree#10]
Hi I love this, was just wondering if it's meant to show colours for directories and such? Mine just come out grey, but your picture looks like they're blue and bold? Modified ones do go yellow so I'm not sure what's up

**Comment by jpwilliams** [comment]
Hmm yeah grey is for _untracked_ files (files not yet checked in) and blue should be folders. Git itself doesn't track folders, so there should be no reason a folder would appear as _grey_.

What terminal/theme/etc are you using? It's likely that it's something like that that's affecting it.

**Comment by ayroblu** [comment]
I'm using the MacOS terminal with a solarized theme, yeah it might be the case, I just thought the colours were coded in so they always turned blue, but maybe it's smarter than that

**Comment by jpwilliams** [comment]
Hmm aye. The underlying library it uses for colouring the output is [chalk/chalk](https://github.com/chalk/chalk) which will wrap the text in colour codes, though different themes will interpret those in different ways.

Looks like there's an older issue (chalk/chalk#40) where grey was appearing invisible, so it'd be fair to assume that it's potentially your Solarized theme that's doing it.

Try switching to a default theme and see if it does it there too?

**Comment by jpwilliams** [comment]
Closing as this doesn't seem like an issue with gitree.
