### ISSUE TITLE
Filter additional given directories as inputs

### ISSUE THREAD

**Issue by ultrox** [jpwilliams/gitree#13]
I love this script, thank you.

I often have a directory containing stuff I need, but usually not super important when looking what's up, how could quickly filter those.

`gt --filter a b c`

Would be absolutely amazing and useful.

PS: Oh..., I'm #13. Like #13 is every solved.

**Comment by jpwilliams** [comment]
@ultrox This is now published in `1.3.0` with the `-I` option introduced in #14.

Please note that the package changed from `gitree` to `@jpwilliams/gitree` (as it's now available on both [npm](https://www.npmjs.com/package/@jpwilliams/gitree) and here on [GPR](https://github.com/jpwilliams/gitree/packages/23584)), so make sure you install the new version!
